name: javelin_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  wifi_scan: ^0.4.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  csv: ^6.0.0
  fl_chart: ^0.65.0
  http: ^1.1.0
  app_settings: ^5.1.0
  wifi_iot: ^0.3.18
  intl: ^0.18.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  vector_math: ^2.1.4
  html: ^0.15.4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - test_data/
